theme = "catppuccin_mocha"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
line-number = "relative"
bufferline = "multiple"
cursor-shape.insert = "bar"

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 